# -*- coding: utf-8 -*-
"""Copy of 3분 만에 만드는 인공지능 서비스: 마동석/김종국/이병헌 분류기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iu9Jwp45n8p15aF29qmehykKP6HLtJgx

refer : https://youtu.be/Lu93Ah2h9XA?si=mANCGbCFFK3JvcNO

### <b>3분 만에 전이 학습(Transfer Learning)을 활용한 인공지능 서비스 만들기</b>

* 본 프로젝트에서는 세 가지 기능을 합쳐서 순식간에 상용 인공지능 서비스를 제작합니다.
    1. 이미지 크롤링(image crawling) 혹은 크롤링 라이브러리
    2. 전이 학습(transfer learning)
    3. 웹 API 개발
* 이 프로젝트에서 만들어 볼 것은 <b>마동석/김종국/이병헌</b> 분류기(classifier)입니다.
* 단 <b>3분</b> 만에 인공지능 개발의 전체 과정을 진행합니다.
    * 데이터 수집/정제
    * 인공지능 모델 학습
    * 학습된 모델 배포
* 한글 폰트 설치 이후에 <b>[런타임] - [런타임 다시 시작]</b>을 수행해야 합니다.
"""

from bing_image_downloader import downloader
from datetime import datetime

# 현재 날짜 및 시간을 얻습니다.
now = datetime.now()

# 원하는 형식으로 날짜와 시간을 문자열로 변환합니다.
date_str = now.strftime("%Y%m%d%H%M%S")

# for
queries = ['건물']
queries = ['건물들', 'buildings']
queries = ["towns", "빌딩숲", "buildings", "건물들"]
output_dir = './datasets/collections/fromBings/'+date_str
for query in queries:
    downloader.download(query, limit=50,  output_dir=output_dir,
                        adult_filter_off=True, force_replace=False, timeout=60)
